package com.safereach.inventory_system.mapper;

import com.safereach.inventory_system.dto.ProductRequest;
import com.safereach.inventory_system.dto.ProductResponse;
import com.safereach.inventory_system.entity.Product;
import org.mapstruct.InjectionStrategy;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring", injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface ProductMapper {

    @Mapping(target = "id", ignore = true) // Assuming ID is generated by the database
    Product toEntity(ProductRequest productRequest);
    ProductResponse toResponse(ProductResponse productModel);
    ProductResponse toResponse(Product product);
}
